title: Seelos Water
description: Water Resources | Environmental | Data Science

url: "https://www.seeloswater.com"
baseurl: ""

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
